### ISSUE TITLE
view distance

### ISSUE THREAD

**Issue by arts7493** [ShaneBeee/Skript-Paper#3]
can't use set view distance of player to ~~
paper 1.15.2
skript 2.4.1

[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[03:28:31] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[03:28:31] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[03:28:31] [Server thread/ERROR]: #!#! Here is full list of them:
[03:28:31] [Server thread/ERROR]: #!#! UtilitySK Skript-Paper (https://github.com/ShaneBeee/Skript-Paper) skRayFall (https://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) SkBee (https://github.com/ShaneBeee/SkBee) SkQuery SkDowngrade Skore SkBentobox Skellett (https://forums.skunity.com/resources/skellett.24/) skript-placeholders (https://github.com/APickledWalrus/skript-placeholders) DiscordSRV (https://github.com/DiscordSRV/DiscordSRV) 
[03:28:31] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[03:28:31] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[03:28:31] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[03:28:31] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[03:28:31] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[03:28:31] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Stack trace:
[03:28:31] [Server thread/ERROR]: #!#! org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement (There are per world view distances though!)
[03:28:31] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.setViewDistance(CraftPlayer.java:1981)
[03:28:31] [Server thread/ERROR]: #!#!     at tk.shanebee.skriptpaper.elements.expressions.ExprPlayerViewDistance.change(ExprPlayerViewDistance.java:68)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
[03:28:31] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[03:28:31] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[03:28:31] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[03:28:31] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:28:31] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1861)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060)
[03:28:31] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[03:28:31] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Version Information:
[03:28:31] [Server thread/ERROR]: #!#!   Skript: 2.4.1
[03:28:31] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[03:28:31] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[03:28:31] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[03:28:31] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[03:28:31] [Server thread/ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[03:28:31] [Server thread/ERROR]: #!#!   OS: Windows Server 2012 R2 amd64 6.3
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Server platform: Paper
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Current node: null
[03:28:31] [Server thread/ERROR]: #!#! Current item: set view distance of the player to the 1st argument
[03:28:31] [Server thread/ERROR]: #!#! Current trigger: command /vd (simple event) (join.sk, line -1)
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Thread: Server thread
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! Language: korean
[03:28:31] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[03:28:31] [Server thread/ERROR]: #!#! 
[03:28:31] [Server thread/ERROR]: #!#! End of Error.
[03:28:31] [Server thread/ERROR]: #!#!

**Comment by ShaneBeee** [comment]
This is an issue with Paper.
They removed per-player view distance, as you can see in the error:
```
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement (There are per world view distances though!)
```

**Comment by arts7493** [comment]
is there no other way?

**Comment by ShaneBeee** [comment]
No, I already said paper removed it. 
I think they're planning on bringing it back, but that's not going to happen for the outdated version of Paper you're running.
